/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package packageStadistics;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
/**
 *
 * @author jose_
 */
public class Statistic extends javax.swing.JInternalFrame {

    /**
     * Creates new form Statistic
     */
    public Statistic() {
        initComponents();
        //show();  
        String text;
        //it sets the labels with the points
        text=generateStatistic("Points1");
        labelStat1.setText(text);
        text=generateStatistic("Points2");
        labelStat2.setText(text);
        text=generateStatistic("Earnings");
        labelStat3.setText(text);
        text=generateStatistic("segundos");
        labelStat4.setText(text);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelStat4 = new javax.swing.JLabel();
        labelGame4 = new javax.swing.JLabel();
        labelGame3 = new javax.swing.JLabel();
        labelStat3 = new javax.swing.JLabel();
        labelGame2 = new javax.swing.JLabel();
        labelStat2 = new javax.swing.JLabel();
        labelGame1 = new javax.swing.JLabel();
        labelStat1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelStat4.setText("stat4");
        jPanel1.add(labelStat4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        labelGame4.setText("Game4");
        jPanel1.add(labelGame4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        labelGame3.setText("Game3");
        jPanel1.add(labelGame3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        labelStat3.setText("stat3");
        jPanel1.add(labelStat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        labelGame2.setText("Game2");
        jPanel1.add(labelGame2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        labelStat2.setText("stat2");
        jPanel1.add(labelStat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        labelGame1.setText("Game1");
        jPanel1.add(labelGame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 39, -1, -1));

        labelStat1.setText("stat1");
        jPanel1.add(labelStat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 380, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //it will search for the greatest score in the list of the game
    public String generateStatistic(String typeScore){
        File f = new File("src\\main\\java\\Classes\\texto.txt");
        String chain;
        Scanner entry = null;
        int great = 0;
        String hScore = "";
        boolean cmp;
        try{
            entry = new Scanner(f);
            while(entry.hasNext()){
                chain = entry.nextLine();
                String[] ver = chain.split(" ");
                cmp = ver[0].contains(typeScore);   //it verifies if the type is in the array   
                if((cmp && great<Integer.valueOf(ver[2]))){
                    great = Integer.valueOf(ver[2]);
                    hScore = chain;
                }
            }
            return hScore;
        }catch(FileNotFoundException e){
            System.out.println(e.getMessage());
        }finally{
            entry.close();
        }       
        return null;        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelGame1;
    private javax.swing.JLabel labelGame2;
    private javax.swing.JLabel labelGame3;
    private javax.swing.JLabel labelGame4;
    private javax.swing.JLabel labelStat1;
    private javax.swing.JLabel labelStat2;
    private javax.swing.JLabel labelStat3;
    private javax.swing.JLabel labelStat4;
    // End of variables declaration//GEN-END:variables
}
