/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package packageG1;
import Classes.GameFunction;
import Classes.Stat;

/**
 *
 * @author jose_
 */
public class Game1 extends javax.swing.JInternalFrame implements GameFunction {

    /**
     * Creates new form MenuG1
     */
    public Game1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelG1 = new javax.swing.JPanel();
        bScoreG1 = new javax.swing.JButton();
        bStartG1 = new javax.swing.JButton();

        bScoreG1.setText("Scores");

        bStartG1.setText("Start game");
        bStartG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStartG1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelG1Layout = new javax.swing.GroupLayout(panelG1);
        panelG1.setLayout(panelG1Layout);
        panelG1Layout.setHorizontalGroup(
            panelG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelG1Layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addGroup(panelG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bStartG1)
                    .addGroup(panelG1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(bScoreG1)))
                .addGap(160, 160, 160))
        );
        panelG1Layout.setVerticalGroup(
            panelG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelG1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(bStartG1)
                .addGap(58, 58, 58)
                .addComponent(bScoreG1)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelG1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelG1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bStartG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStartG1ActionPerformed
        // TODO add your handling code here:
        start();
    }//GEN-LAST:event_bStartG1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bScoreG1;
    private javax.swing.JButton bStartG1;
    private javax.swing.JPanel panelG1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void start() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Stat getStats() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
