/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
//importing the packages of the games
import Classes.Stat;
import packageG1.Game1;
import packageG2.Game2;
import packageG3.Game3;
import packageStadistics.Statistic;
import Singleton.*;
/**
 *
 * @author jose_
 */
public class Window extends javax.swing.JFrame {
    private Game1 g1 = SingletonG1.getInstance();
    private Game2 g2= SingletonG2.getInstance();
    private Game3 g3= SingletonG3.getInstance();
    private Statistic s = new Statistic();
    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        DesktopPane.add(this.g1);
        DesktopPane.add(this.g2);
        DesktopPane.add(this.g3);
        DesktopPane.add(this.s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPane = new javax.swing.JDesktopPane();
        welcomeLabel = new javax.swing.JLabel();
        Game1 = new javax.swing.JButton();
        Game2 = new javax.swing.JButton();
        Game3 = new javax.swing.JButton();
        Game4 = new javax.swing.JButton();
        bStatistics = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(DesktopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 0, -1, 301));

        welcomeLabel.setForeground(new java.awt.Color(102, 0, 255));
        welcomeLabel.setText("Welcome!");
        getContentPane().add(welcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 11, -1, -1));

        Game1.setText("Game1");
        Game1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Game1ActionPerformed(evt);
            }
        });
        getContentPane().add(Game1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 59, -1, -1));

        Game2.setText("Game2");
        Game2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Game2ActionPerformed(evt);
            }
        });
        getContentPane().add(Game2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 93, -1, -1));

        Game3.setText("Game3");
        Game3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Game3ActionPerformed(evt);
            }
        });
        getContentPane().add(Game3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 127, -1, -1));

        Game4.setText("Game4");
        getContentPane().add(Game4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 168, -1, -1));

        bStatistics.setText("Statistics");
        bStatistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStatisticsActionPerformed(evt);
            }
        });
        getContentPane().add(bStatistics, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 209, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Game1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Game1ActionPerformed
        //here will be the instance of the fist game 
        //this.g1.reset();
        this.g1.setVisible(true); 
        this.g2.setVisible(false); 
        this.g3.setVisible(false); 
    }//GEN-LAST:event_Game1ActionPerformed

    private void Game2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Game2ActionPerformed
        // TODO add your handling code here:  

        this.g2.setVisible(true);
        this.g1.setVisible(false); 
        this.g3.setVisible(false); 
    }//GEN-LAST:event_Game2ActionPerformed

    private void Game3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Game3ActionPerformed
        // TODO add your handling code here: 

        this.g3.setVisible(true);
        this.g2.setVisible(false); 
        this.g1.setVisible(false); 
    }//GEN-LAST:event_Game3ActionPerformed

    private void bStatisticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStatisticsActionPerformed
        // TODO add your handling code here:
       
        this.s.setVisible(true);
        this.g1.setVisible(false); 
        this.g2.setVisible(false); 
        this.g3.setVisible(false); 
    }//GEN-LAST:event_bStatisticsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Window().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JButton Game1;
    private javax.swing.JButton Game2;
    private javax.swing.JButton Game3;
    private javax.swing.JButton Game4;
    private javax.swing.JButton bStatistics;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
